using System;
using UnityEngine;

namespace DG.Tweening.Core
{
	// Token: 0x0200004B RID: 75
	public static class Debugger
	{
		// Token: 0x17000009 RID: 9
		// (get) Token: 0x06000283 RID: 643 RVA: 0x0000E93C File Offset: 0x0000CB3C
		public static int logPriority
		{
			get
			{
				return Debugger._logPriority;
			}
		}

		// Token: 0x06000284 RID: 644 RVA: 0x0000E943 File Offset: 0x0000CB43
		public static void Log(object message)
		{
			message = "<color=#0099bc><b>DOTWEEN ► </b></color>" + ((message != null) ? message.ToString() : null);
			if (DOTween.onWillLog != null && !DOTween.onWillLog(LogType.Log, message))
			{
				return;
			}
			Debug.Log(message);
		}

		// Token: 0x06000285 RID: 645 RVA: 0x0000E97C File Offset: 0x0000CB7C
		public static void LogWarning(object message, Tween t = null)
		{
			message = "<color=#0099bc><b>DOTWEEN ► </b></color>" + ((message != null) ? message.ToString() : null);
			if (DOTween.debugMode && t != null)
			{
				bool flag = t.debugTargetId != null;
				bool flag2 = t.stringId != null;
				bool flag3 = t.intId != -999;
				if (flag || flag2 || flag3)
				{
					message = ((message != null) ? message.ToString() : null) + "\n";
					if (flag)
					{
						message = ((message != null) ? message.ToString() : null) + string.Format("-[debug target ID: {0}]-", t.debugTargetId);
					}
					if (flag2)
					{
						message = ((message != null) ? message.ToString() : null) + string.Format("-[stringId: {0}]-", t.stringId);
					}
					if (flag3)
					{
						message = ((message != null) ? message.ToString() : null) + string.Format("-[intId: {0}]-", t.intId);
					}
				}
			}
			if (DOTween.onWillLog != null && !DOTween.onWillLog(LogType.Warning, message))
			{
				return;
			}
			Debug.LogWarning(message);
		}

		// Token: 0x06000286 RID: 646 RVA: 0x0000EA8B File Offset: 0x0000CC8B
		public static void LogError(object message)
		{
			message = "<color=#0099bc><b>DOTWEEN ► </b></color>" + ((message != null) ? message.ToString() : null);
			if (DOTween.onWillLog != null && !DOTween.onWillLog(0, message))
			{
				return;
			}
			Debug.LogError(message);
		}

		// Token: 0x06000287 RID: 647 RVA: 0x0000EAC1 File Offset: 0x0000CCC1
		public static void LogReport(object message)
		{
			message = string.Format("<color=#00B500FF>{0} REPORT ►</color> {1}", "<color=#0099bc><b>DOTWEEN ► </b></color>", message);
			if (DOTween.onWillLog != null && !DOTween.onWillLog(LogType.Log, message))
			{
				return;
			}
			Debug.Log(message);
		}

		// Token: 0x06000288 RID: 648 RVA: 0x0000EAF1 File Offset: 0x0000CCF1
		public static void LogSafeModeReport(object message)
		{
			message = string.Format("<color=#ff7337>{0} SAFE MODE ►</color> {1}", "<color=#0099bc><b>DOTWEEN ► </b></color>", message);
			if (DOTween.onWillLog != null && !DOTween.onWillLog(LogType.Log, message))
			{
				return;
			}
			Debug.LogWarning(message);
		}

		// Token: 0x06000289 RID: 649 RVA: 0x0000EB21 File Offset: 0x0000CD21
		public static void LogInvalidTween(Tween t)
		{
			Debugger.LogWarning("This Tween has been killed and is now invalid", null);
		}

		// Token: 0x0600028A RID: 650 RVA: 0x0000EB2E File Offset: 0x0000CD2E
		public static void LogNestedTween(Tween t)
		{
			Debugger.LogWarning("This Tween was added to a Sequence and can't be controlled directly", t);
		}

		// Token: 0x0600028B RID: 651 RVA: 0x0000EB3B File Offset: 0x0000CD3B
		public static void LogNullTween(Tween t)
		{
			Debugger.LogWarning("Null Tween", null);
		}

		// Token: 0x0600028C RID: 652 RVA: 0x0000EB48 File Offset: 0x0000CD48
		public static void LogNonPathTween(Tween t)
		{
			Debugger.LogWarning("This Tween is not a path tween", t);
		}

		// Token: 0x0600028D RID: 653 RVA: 0x0000EB55 File Offset: 0x0000CD55
		public static void LogMissingMaterialProperty(string propertyName)
		{
			Debugger.LogWarning(string.Format("This material doesn't have a {0} property", propertyName), null);
		}

		// Token: 0x0600028E RID: 654 RVA: 0x0000EB68 File Offset: 0x0000CD68
		public static void LogMissingMaterialProperty(int propertyId)
		{
			Debugger.LogWarning(string.Format("This material doesn't have a {0} property ID", propertyId), null);
		}

		// Token: 0x0600028F RID: 655 RVA: 0x0000EB80 File Offset: 0x0000CD80
		public static void LogRemoveActiveTweenError(string errorInfo, Tween t)
		{
			Debugger.LogWarning(string.Format("Error in RemoveActiveTween ({0}). It's been taken care of so no problems, but Daniele (DOTween's author) is trying to pinpoint it (it's very rare and he can't reproduce it) so it would be awesome if you could reproduce this log in a sample project and send it to him. Or even just write him the complete log that was generated by this message. Fixing this would make DOTween slightly faster. Thanks.", errorInfo), t);
		}

		// Token: 0x06000290 RID: 656 RVA: 0x0000EB93 File Offset: 0x0000CD93
		public static void LogAddActiveTweenError(string errorInfo, Tween t)
		{
			Debugger.LogWarning(string.Format("Error in AddActiveTween ({0}). It's been taken care of so no problems, but Daniele (DOTween's author) is trying to pinpoint it (it's very rare and he can't reproduce it) so it would be awesome if you could reproduce this log in a sample project and send it to him. Or even just write him the complete log that was generated by this message. Fixing this would make DOTween slightly faster. Thanks.", errorInfo), t);
		}

		// Token: 0x06000291 RID: 657 RVA: 0x0000EBA6 File Offset: 0x0000CDA6
		public static void SetLogPriority(LogBehaviour logBehaviour)
		{
			if (logBehaviour == LogBehaviour.Default)
			{
				Debugger._logPriority = 1;
				return;
			}
			if (logBehaviour != LogBehaviour.Verbose)
			{
				Debugger._logPriority = 0;
				return;
			}
			Debugger._logPriority = 2;
		}

		// Token: 0x04000139 RID: 313
		private static int _logPriority;

		// Token: 0x0400013A RID: 314
		private const string _LogPrefix = "<color=#0099bc><b>DOTWEEN ► </b></color>";
	}
}
